-- MySQL Script generated by MySQL Workbench
-- Fri May  3 06:17:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `codigo_producto` BIGINT(20) NOT NULL ,
  `nombre` VARCHAR(50) NULL,
  `proveedor` VARCHAR(32) NOT NULL,
  `descripcion` TEXT NULL,
  `cantidad_en_stock` SMALLINT NULL,
  `precio_venta` DECIMAL(15,2) NULL,
  `precio_proveedor` DECIMAL(15,2) NULL,
  `id_productos` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_productos`, `id_productos`)
);



-- -----------------------------------------------------
-- Table `mydb`.`recetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recetas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recetas` (
  `id_recetas` INT NOT NULL AUTO_INCREMENT,
  `codigo_receta` BIGINT(20) NOT NULL,
  `ingredientes` VARCHAR(255) NOT NULL,
  `receta` TEXT NULL,
  `imagen` BLOB NULL,
  PRIMARY KEY (`codigo_receta`),
  CONSTRAINT `fk_recetas_1`
    FOREIGN KEY (`codigo_receta`)
    REFERENCES `mydb`.`producto` (`codigo_receta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pago` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pago` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `codigo_cliente` BIGINT(20) NOT NULL,
  `codigo_pago` BIGINT(20) NOT NULL,
  `forma_pago` VARCHAR(50) NULL,
  `fecha_pago` DATE NULL DEFAULT CURRENT_TIMESTAMP,
  `total` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`codigo_cliente`, `codigo_pago`));


-- -----------------------------------------------------
-- Table `mydb`.`menu_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`menu_items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`menu_items` (
  `id_menu` INT NULL AUTO_INCREMENT,
  `codigo_menu` BIGINT(20) NOT NULL,
  `receta` TEXT NOT NULL,
  `imagen` BLOB NULL,
  `codigo_receta` BIGINT(20) NOT NULL,
  `precio` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_menu`, `codigo_receta`),
  INDEX `id_recetas_idx` (`codigo_receta` ASC) VISIBLE,
  CONSTRAINT `id_recetas`
    FOREIGN KEY (`codigo_receta`)
    REFERENCES `mydb`.`recetas` (`codigo_receta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NULL AUTO_INCREMENT,
  `codigo_cliente` BIGINT(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `segundo_nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `dni` INT NOT NULL,
  `codigo_postal` SMALLINT NOT NULL,
  `codigo_representante_venta` INT NOT NULL,
  PRIMARY KEY (`codigo_cliente`, `codigo_representante_venta`),
  CONSTRAINT `fk_pagos_copy1_1`
    FOREIGN KEY (`codigo_cliente`)
    REFERENCES `mydb`.`pago` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `codigo_pedido` BIGINT(20) NOT NULL,
  `fecha_pedido` DATE NOT NULL,
  `fecha_esperada` DATE NULL,
  `fecha_entrega` DATE NULL,
  `estado` VARCHAR(45) NULL,
  `comentarios` TEXT NULL,
  `codigo_proveedor` BIGINT(20) NOT NULL,
  PRIMARY KEY (`codigo_pedido`, `codigo_proveedor`));


-- -----------------------------------------------------
-- Table `mydb`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proveedores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proveedores` (
  `id_proveedores` INT NOT NULL AUTO_INCREMENT,
  `codigo_proveedor` BIGINT(20) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `telefono` VARCHAR(15) NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(50) NULL,
  `region` VARCHAR(50) NULL,
  `pais` VARCHAR(15) NULL,
  `codigo_postal` SMALLINT NULL,
  PRIMARY KEY (`codigo_proveedor`),
  CONSTRAINT `fk_proveedores_1`
    FOREIGN KEY (`codigo_proveedor`)
    REFERENCES `mydb`.`producto` (`codigo_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedores_2`
    FOREIGN KEY ()
    REFERENCES `mydb`.`pedido` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`empleado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `codigo_empleado` BIGINT(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `extension` VARCHAR(50) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(15) NULL,
  `codigo_oficina` BIGINT(20) NOT NULL,
  `codigo_jefe` INT NULL,
  PRIMARY KEY (`codigo_empleado`, `codigo_oficina`),
  CONSTRAINT `fk_empleado_1`
    FOREIGN KEY (`codigo_empleado`)
    REFERENCES `mydb`.`cliente` (`codigo_representante_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`oficina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`oficina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`oficina` (
  `codigo_oficina` BIGINT(20) NOT NULL,
  `ciudad` VARCHAR(15) NOT NULL,
  `pais` VARCHAR(15) NOT NULL,
  `region` VARCHAR(15) NOT NULL,
  `codigo_postal` SMALLINT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `direccion2` VARCHAR(45) NULL,ne auto
  `telefono` VARCHAR(45) NULL,
  `codigo_jefe_oficina` INT NOT NULL,
  `id_oficina` INT NULL AUTO_INCREMENT,
  PRIMARY KEY (`codigo_oficina`, `codigo_jefe_oficina`),
  INDEX `fk_oficina_2_idx` (`codigo_jefe_oficina` ASC) VISIBLE,
  CONSTRAINT `fk_oficina_1`
    FOREIGN KEY (`codigo_oficina`)
    REFERENCES `mydb`.`empleado` (`codigo_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oficina_2`
    FOREIGN KEY (`codigo_jefe_oficina`)
    REFERENCES `mydb`.`empleado` (`codigo_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`detalle_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`detalle_pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`detalle_pedido` (
  `id_detalle_pedido` INT NULL AUTO_INCREMENT,
  `codigo_pedido` BIGINT(20) NOT NULL,
  `codigo_producto` BIGINT(20) NOT NULL,
  `cantidad` INT NULL,
  `precio_unidad` SMALLINT NULL,
  `detalle_pedidocol` DECIMAL(15,2) NULL,
  PRIMARY KEY (`codigo_pedido`, `codigo_producto`),
  INDEX `fk_pedido_copy1_2_idx` (`codigo_producto` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_copy1_1`
    FOREIGN KEY (`codigo_pedido`)
    REFERENCES `mydb`.`pedido` (`codigo_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_copy1_2`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `mydb`.`producto` (`codigo_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`orden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orden` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orden` (
  `idorden` INT NOT NULL AUTO_INCREMENT,
  `codigo_orden` BIGINT(20) NOT NULL,
  `codigo_cliente` BIGINT(20) NOT NULL,
  `impuestos` VARCHAR(45) NULL,
  `descuentos` VARCHAR(45) NULL,
  `subtotal_orden` VARCHAR(45) NULL,
  `orden_detalles` VARCHAR(45) NULL,
  `cuit` VARCHAR(45) NULL,
  `firma` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_cliente`, `codigo_orden`, `idorden` ),
  CONSTRAINT `fk_orden_1`
    FOREIGN KEY (`codigo_cliente`)
    REFERENCES `mydb`.`cliente` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deposito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`deposito` ;

CREATE TABLE IF NOT EXISTS `mydb`.`deposito` (
  `iddeposito` INT NOT NULL AUTO_INCREMENT,
  `codigo_deposito` BIGINT(20) NOT NULL,
  `codigo_producto` BIGINT(20) NOT NULL,
  `codigo_encargado_deposito` INT NOT NULL,
  `cantidad_en_stock_actual` INT NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_deposito`, `codigo_producto`, `codigo_encargado_deposito`),
  INDEX `fk_deposito_1_idx` (`codigo_producto` ASC) VISIBLE,
  INDEX `fk_deposito_2_idx` (`codigo_encargado_deposito` ASC) VISIBLE,
  CONSTRAINT `fk_deposito_1`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `mydb`.`producto` (`codigo_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deposito_2`
    FOREIGN KEY (`codigo_encargado_deposito`)
    REFERENCES `mydb`.`empleado` (`codigo_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



